export const ADD_CONTACT = 'ADD _CONTACT';
export const DELETE_CONTACT = 'DELETE _CONTACT';
export const SET_CURRENT = 'SET _CURRENT';
export const CLEAR_CURRENT = 'CLEAR _CURRENT';
export const UPDATE_CONTACT = 'UPDATE _CONTACT';
export const FILTER_CONTACTS = 'FILTER_CONTACTS';
export const CLEAR_FILTER = 'CLEAR _FILTER';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
